#
# This file contains configurations for your blog site
#

# NAME OF YOUR SITE
name: "KeKe Blog"
# Short bio
description: "个人技术学习笔记"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://github.com/lemonchann/images/raw/master/gzh/%E6%96%87%E6%9C%AB%E6%8E%A8%E5%B9%BF%E6%96%87%E6%A1%88.png
# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://github.com/lemonchann/lemonchann.github.io/raw/master/images/favicon.ico

# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags

# Pagination
paginate: 8

# Includes an icon in the footer for each username you enter
footer-links:
  email: kathy@enc.hanyang.ac.kr.com
  github: kekeMemory 
  CSDN: https://blog.csdn.net/keke_Memory
